# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: You Know What I Like...? Podcast
email: ykwilpodcast@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Do you get overly attached to things without any real explanation of why? Then
  this is the podcast for you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ykwilpodcast.com" # the base hostname & protocol for your site
twitter_username: ykwilpodcast
github_username:  ykwilpodcast

# Build settings
markdown: kramdown
